baseURL = "https://bubbuls.github.io/"
languageCode = "fr-fr"
title = "Kevin ALBRECHT"
theme = "hyde-hyde"
googleAnalytics = "UA-118690818-1"
disqusShortname = "kalbrecht-blog"
	[menu]
		[[menu.main]]
		    name = "Blog posts"
		    pre = "<i class='fa fa-list-ul'></i>"
		    url = "/"
		    weight = -10
#		[[menu.main]]
#			identifier = "about"
#			name = "A propos de moi"
#			pre = "<i class='fa fa-user'></i>"
#			url = "/about/"
#			weight = -9

	[params]
	authorimage ="/author.jpg"
	description = "Développeur web"
	at = "@Infinitesquare"
	atlink = "https://infinitesquare.com/"
	dateformat = "02/01/2006"

		[[params.technos]]
		preclass= "fab fa-angular"
		title="Angular"
		[[params.technos]]
		preclass= "fab fa-windows"
		title="Asp.net / Core"
		[[params.technos]]
		preclass= "fa fa-mobile-alt"
		title="Cordova"

		[params.niconico]
		baseuri = "http://nicovideo.cdn.nimg.jp/web/img/base/head/icon/nico/"
		ids = [
			"000","005","007","008","010", "011","012","013","014",
			"015","016","018","019","020","022","023","024","026",
			"028","031","032","033","034","035","038","039","040",
			"046","050","052","053","058","061","063","075","078",
			"089","092","094","104","118","127","131","132","135"
		]

		[params.social]
		twitter = "kalbrecht_fr"
		github = "Bubbuls"
		linkedin = "albrechtkevin/"
		email = "kevin-albrecht@outlook.fr"