baseURL = "https://KevinALBRECHT.github.io/"
# DefaultContentLanguage = "en"
theme = "hyde-hyde"
googleAnalytics = "UA-118690818-1"
disqusShortname = "kalbrecht-blog"
summaryLength = 30
	[languages]
		[languages.en]
			title = "Kevin ALBRECHT"
			description="Fullstack developer"
			languageName = "English"
			[languages.en.params]
					dateformat = "01/02/2006"
			[[languages.en.menu.main]]
				name = "Blog posts"
		    	pre = "<i class='fa fa-list-ul'></i>"
				url = "/en/"
		    	weight = -10
			[[languages.en.menu.main]]
				name = "About"
		    	pre = "<i class='fa fa-user'></i>"
				url = "about"
  				weight = -9
		[languages.fr]
			title = "Kevin ALBRECHT"
			description="Développeur Fullstack"
			languageName = "Français"
			[languages.fr.params]
				dateformat = "02/01/2006"
			[[languages.fr.menu.main]]
				name = "Blog posts"
		    	pre = "<i class='fa fa-list-ul'></i>"
				url = "/fr/"
		    	weight = -10
			[[languages.fr.menu.main]]
				name = "A propos"
				pre = "<i class='fa fa-user'></i>"
				url = "about"
  				weight = -9
		[languages.ja]
			title = "アルブレシュと・ケビン"
			description="フルスタックエンジニア"
			languageName = "日本語"
			[languages.ja.params]
				dateformat = "2006/02/01"
			[[languages.ja.menu.main]]
				name = "記事"
		    	pre = "<i class='fa fa-list-ul'></i>"
				url = "/ja/"
		    	weight = -10
			[[languages.ja.menu.main]]
				name = "情報"
				pre = "<i class='fa fa-user'></i>"
				url = "about"
  				weight = -9
	[permalinks]
		posts= "/:section/:slug"
		about="/:title"
		home="/posts"
	[params]
		authorimage ="/author.jpg"
		at = "@Infinitesquare"
		atlink = "https://infinitesquare.com/"
		dateformat = "02/01/2006"
	[[params.technos]]
		preclass= "fab fa-angular"
		title="Angular"
	[[params.technos]]
		preclass= "fab fa-windows"
		title="Asp.net / Core"
	[[params.technos]]
		preclass= "fa fa-mobile-alt"
		title="Cordova"
	[params.niconico]
		baseuri = "http://nicovideo.cdn.nimg.jp/web/img/base/head/icon/nico/"
		ids = [
			"000","005","007","008","010", "011","012","013","014",
			"015","016","018","019","020","022","023","024","026",
			"028","031","032","033","034","035","038","039","040",
			"046","050","052","053","058","061","063","075","078",
			"089","092","094","104","118","127","131","132","135"
		]
	[params.social]
		twitter = "kalbrecht_fr"
		github = "KevinALBRECHT"
		linkedin = "albrechtkevin/"
		email = "kevin.albrecht@outlook.fr"